# Generated by Django 5.0.7 on 2024-12-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrationapp', '0003_patientlist_delete_patientslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientlist',
            name='Time',
            field=models.DateField(),
        ),
    ]
