# Generated by Django 5.0.7 on 2024-12-07 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrationapp', '0004_alter_patientlist_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientlist',
            old_name='Time',
            new_name='Date',
        ),
    ]
